### ISSUE TITLE
Nextcloud Postgres - container restart failed

### ISSUE THREAD

**Issue by thiesschneider** [Wonderfall/dockerfiles#69]
Hi,

I tried to build nextcloud with the official postgres container and everything works fine.
But when I try to restart the container Nextcloud is not able to start.

My docker logs:

> An unhandled exception has been thrown:
Doctrine\DBAL\DBALException: Failed to connect to the database: An exception occured in driver: SQLSTATE[08006] [7] could not connect to server: Connection refused
	Is the server running on host "db_nextcloud" (172.17.0.8) and accepting
	TCP/IP connections on port 5432? in /nextcloud/lib/private/DB/Connection.php:59
Stack trace:
#0 /nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(429): OC\DB\Connection->connect()
#1 /nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(389): Doctrine\DBAL\Connection->getDatabasePlatformVersion()
#2 /nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(328): Doctrine\DBAL\Connection->detectDatabasePlatform()
#3 /nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(621): Doctrine\DBAL\Connection->getDatabasePlatform()
#4 /nextcloud/lib/private/DB/Connection.php(142): Doctrine\DBAL\Connection->setTransactionIsolation(2)
#5 /nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DriverManager.php(172): OC\DB\Connection->__construct(Array, Object(Doctrine\DBAL\Driver\PDOPgSql\Driver), Object(Doctrine\DBAL\Configuration), Object(Doctrine\Common\EventManager))
#6 /nextcloud/lib/private/DB/ConnectionFactory.php(121): Doctrine\DBAL\DriverManager::getConnection(Array, Object(Doctrine\DBAL\Configuration), Object(Doctrine\Common\EventManager))
#7 /nextcloud/lib/private/Server.php(415): OC\DB\ConnectionFactory->getConnection('pgsql', Array)
#8 /nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(113): OC\Server->OC\{closure}(Object(OC\Server))
#9 /nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(103): Pimple\Container->offsetGet('DatabaseConnect...')
#10 /nextcloud/lib/private/ServerContainer.php(89): OC\AppFramework\Utility\SimpleContainer->query('DatabaseConnect...')
#11 /nextcloud/lib/private/Server.php(1029): OC\ServerContainer->query('DatabaseConnect...')
#12 /nextcloud/lib/private/Server.php(220): OC\Server->getDatabaseConnection()
#13 /nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(113): OC\Server->OC\{closure}(Object(OC\Server))
#14 /nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(103): Pimple\Container->offsetGet('OC\\Authenticati...')
#15 /nextcloud/lib/private/ServerContainer.php(89): OC\AppFramework\Utility\SimpleContainer->query('OC\\Authenticati...')
#16 /nextcloud/lib/private/Server.php(224): OC\ServerContainer->query('OC\\Authenticati...')
#17 /nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(113): OC\Server->OC\{closure}(Object(OC\Server))
#18 /nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(103): Pimple\Container->offsetGet('OC\\Authenticati...')
#19 /nextcloud/lib/private/ServerContainer.php(89): OC\AppFramework\Utility\SimpleContainer->query('OC\\Authenticati...')
#20 /nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(151): OC\ServerContainer->query('OC\\Authenticati...')
#21 /nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(109): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(OC\Server))
#22 /nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(103): Pimple\Container->offsetGet('OC\\Authenticati...')
#23 /nextcloud/lib/private/ServerContainer.php(89): OC\AppFramework\Utility\SimpleContainer->query('OC\\Authenticati...')
#24 /nextcloud/lib/private/Server.php(239): OC\ServerContainer->query('OC\\Authenticati...')
#25 /nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(113): OC\Server->OC\{closure}(Object(OC\Server))
#26 /nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(103): Pimple\Container->offsetGet('UserSession')
#27 /nextcloud/lib/private/ServerContainer.php(89): OC\AppFramework\Utility\SimpleContainer->query('UserSession')
#28 /nextcloud/lib/private/Server.php(906): OC\ServerContainer->query('UserSession')
#29 /nextcloud/lib/private/Server.php(459): OC\Server->getUserSession()
#30 /nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(113): OC\Server->OC\{closure}(Object(OC\Server))
#31 /nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(103): Pimple\Container->offsetGet('AppManager')
#32 /nextcloud/lib/private/ServerContainer.php(89): OC\AppFramework\Utility\SimpleContainer->query('AppManager')
#33 /nextcloud/lib/private/Server.php(1206): OC\ServerContainer->query('AppManager')
#34 /nextcloud/lib/private/legacy/app.php(293): OC\Server->getAppManager()
#35 /nextcloud/lib/private/legacy/app.php(109): OC_App::getEnabledApps()
#36 /nextcloud/lib/base.php(658): OC_App::loadApps(Array)
#37 /nextcloud/lib/base.php(1059): OC::init()
#38 /nextcloud/console.php(48): require_once('/nextcloud/lib/...')
#39 /nextcloud/occ(11): require_once('/nextcloud/cons...')
#40 {main}

If I delete the config I can rebuild the container and you can see the welcomescreen.
Any Idea how to fix this?

**Comment by thiesschneider** [comment]
If anyone encounters this: I needed to have a dockervolume for the database. If you store the data on the filesystem this above happens.
